# -*- Mode: makefile-gmake -*-

all:
%:
	@$(MAKE) -C test_basic $*
	@$(MAKE) -C test_cavp_aes $*
	@$(MAKE) -C test_cipher_aes $*
	@$(MAKE) -C test_cipher_rsa $*
	@$(MAKE) -C test_digest $*
	@$(MAKE) -C test_hmac $*
	@$(MAKE) -C test_input $*
	@$(MAKE) -C test_key_aes $*
	@$(MAKE) -C test_key_rsa $*
	@$(MAKE) -C test_output $*
	@$(MAKE) -C test_sign $*
