#!/bin/bash
#
# This script requires lcov to be installed
#

LIBFOIL_TESTS="\
test_basic \
test_cavp_aes \
test_cavp_cmac \
test_cavp_des \
test_cipher \
test_cipher_aes \
test_cipher_des \
test_cipher_rsa \
test_cmac \
test_digest \
test_hmac \
test_input \
test_key_aes \
test_key_des \
test_key_rsa \
test_output \
test_sign"

LIBFOILMSG_TESTS="\
test_foilmsg"

FLAVOR="coverage"

function require() {
    if ! which $1 >> /dev/null ; then
        echo "*** Please install $1 first!"
        exit 1
    fi
}

# Check required tools
require lcov
require dirname
require realpath

# LCOV 1.10 has branch coverage disabled per default
# Previous versions didn't have the --rc option
if  [ ! -z "$(lcov --help | grep ' --rc ')" ] ; then
    LCOV_OPT="--rc lcov_branch_coverage=1"
    GENHTML_OPT="--branch-coverage"
fi

COV_DIR=$(realpath "$(dirname $0)")
TEST_DIR=$(realpath "${COV_DIR}/..")
BASE_DIR=$(realpath "${TEST_DIR}/..")

LIBFOIL_DIR="$BASE_DIR/libfoil"
LIBFOILMSG_DIR="$BASE_DIR/libfoilmsg"
LIBFOIL_BUILD_DIR="$LIBFOIL_DIR/build/$FLAVOR"
LIBFOILMSG_BUILD_DIR="$LIBFOILMSG_DIR/build/$FLAVOR"

export LD_LIBRARY_PATH="$LIBFOIL_BUILD_DIR"

make -C "$LIBFOIL_DIR" clean $FLAVOR || exit 1
make -C "$LIBFOILMSG_DIR" clean $FLAVOR || exit 1
for t in $LIBFOIL_TESTS ; do
    pushd "$TEST_DIR/libfoil/$t"
    make clean $FLAVOR || exit 1
    build/$FLAVOR/$t || exit 1
    popd
done
for t in $LIBFOILMSG_TESTS ; do
    pushd "$TEST_DIR/libfoilmsg/$t"
    make clean $FLAVOR || exit 1
    build/$FLAVOR/$t || exit 1
    popd
done

LIBFOIL_RAW_COV="$COV_DIR/libfoil-raw.gcov"
LIBFOIL_COV="$COV_DIR/libfoil.gcov"
LIBFOILMSG_RAW_COV="$COV_DIR/libfoilmsg-raw.gcov"
LIBFOILMSG_COV="$COV_DIR/libfoilmsg.gcov"

rm -f "$LIBFOIL_COV" "$LIBFOIL_RAW_COV"  "$LIBFOILMSG_COV" "$LIBFOILMSG_RAW_COV"
lcov $LCOV_OPT -c -d "$LIBFOIL_BUILD_DIR" -b "$LIBFOIL_DIR" -o "$LIBFOIL_RAW_COV" || exit 1
lcov $LCOV_OPT -c -d "$LIBFOILMSG_BUILD_DIR" -b "$LIBFOILMSG_DIR" -o "$LIBFOILMSG_RAW_COV" || exit 1
lcov $LCOV_OPT -e "$LIBFOIL_RAW_COV" "$LIBFOIL_DIR/*" -o "$LIBFOIL_COV" || exit 1
lcov $LCOV_OPT -e "$LIBFOILMSG_RAW_COV" "$LIBFOILMSG_DIR/*" -o "$LIBFOILMSG_COV" || exit 1
genhtml $GENHTML_OPT "$LIBFOIL_COV" "$LIBFOILMSG_COV" -t Foil -p "$BASE_DIR" --output-directory "$COV_DIR/results" || exit 1
