# -*- Mode: makefile-gmake -*-

.PHONY: libfoilmsg-debug libfoilmsg-release libfoilmsg-coverage

QUIET_MAKE = make --no-print-directory

LIBFOILMSG_DIR ?= ../../../libfoilmsg

INCLUDES += -I$(LIBFOILMSG_DIR)/include -I$(LIBFOILMSG_DIR)/src

DEBUG_ORDER_DEPS += libfoilmsg-debug
RELEASE_ORDER_DEPS += libfoilmsg-release
COVERAGE_ORDER_DEPS += libfoilmsg-coverage

DEBUG_LIBFOILMSG_FILE := $(shell $(QUIET_MAKE) -C $(LIBFOILMSG_DIR) print_debug_lib)
RELEASE_LIBFOILMSG_FILE := $(shell $(QUIET_MAKE) -C $(LIBFOILMSG_DIR) print_release_lib)
COVERAGE_LIBFOILMSG_FILE := $(shell $(QUIET_MAKE) -C $(LIBFOILMSG_DIR) print_coverage_lib)

DEBUG_FOILMSG_LIB += $(LIBFOILMSG_DIR)/$(DEBUG_LIBFOILMSG_FILE)
RELEASE_FOILMSG_LIB += $(LIBFOILMSG_DIR)/$(RELEASE_LIBFOILMSG_FILE)
COVERAGE_FOILMSG_LIB += $(LIBFOILMSG_DIR)/$(COVERAGE_LIBFOILMSG_FILE)

DEBUG_LIBS += $(DEBUG_FOILMSG_LIB)
RELEASE_LIBS += $(RELEASE_FOILMSG_LIB)
COVERAGE_LIBS += $(COVERAGE_FOILMSG_LIB)

DEBUG_DEPS += $(DEBUG_FOILMSG_LIB)
RELEASE_DEPS += $(RELEASE_FOILMSG_LIB)
COVERAGE_DEPS += $(COVERAGE_FOILMSG_LIB)

include $(COMMON_DIR)/Makefile

libfoilmsg-debug:
	@make $(SUBMAKE_OPTS) -C $(LIBFOILMSG_DIR) debug

libfoilmsg-release:
	@make $(SUBMAKE_OPTS) -C $(LIBFOILMSG_DIR) release

libfoilmsg-coverage:
	@make $(SUBMAKE_OPTS) -C $(LIBFOILMSG_DIR) coverage
