# -*- Mode: makefile-gmake -*-

QUIET_MAKE = make --no-print-directory

LIBFOILMSG_DIR ?= ../../../libfoilmsg

DEBUG_LIBFOILMSG_FILE := $(shell $(QUIET_MAKE) -C $(LIBFOILMSG_DIR) print_debug_lib)
RELEASE_LIBFOILMSG_FILE := $(shell $(QUIET_MAKE) -C $(LIBFOILMSG_DIR) print_release_lib)

INCLUDES += -I$(LIBFOILMSG_DIR)/include -I$(LIBFOILMSG_DIR)/src
DEBUG_LIBS += $(LIBFOILMSG_DIR)/$(DEBUG_LIBFOILMSG_FILE)
RELEASE_LIBS += $(LIBFOILMSG_DIR)/$(RELEASE_LIBFOILMSG_FILE)
DEBUG_DEPS += libfoilmsg-debug
RELEASE_DEPS += libfoilmsg-release

include $(COMMON_DIR)/Makefile

libfoilmsg-debug:
	@make $(SUBMAKE_OPTS) -C $(LIBFOILMSG_DIR) debug

libfoilmsg-release:
	@make $(SUBMAKE_OPTS) -C $(LIBFOILMSG_DIR) release
